### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [brauerbl/tc359_project6#1]
I'm seeing some pretty inconsistent indentation [in `index.erb`](https://github.com/brauerbl/tc359_project6/blob/master/views/index.erb). Some parts of the file are only using hard-tabs, some are only using soft-tabs - and even within that there are some inconsistencies. Can you fix this here please, then let me know once you've updated the repo? Let me know if you're not sure how.

**Comment by brauerbl** [comment]
The bad indentation is fixed now in this project and the previous two. I'm not sure what the cause of the problem was as it looked correct in sublime but I'll be sure to keep things consistent in the future.

**Comment by chrisvfritz** [comment]
That looks much better. :+1: :smiley: I think [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) should probably make it easier to fix (and prevent) weird indentation in the future. Let me know if you find it useful!
